from random import choice
import time
from Components.Minion import Minion

def btc_token(self, minion, target, buff,  direction, isHuman):
    token_place = 0
    for _ in range(self.brann):
        if len(self.board) < 7:
            is_gold = True if minion.gold else False
            for token in range((2**self.n_khadgar)*(3**self.n_g_khadgar)):
                if len(self.board) < 7:
                    self.timing_IA()
                    token_place += 1
                    minion_token = Minion(minion.qn+'_t', is_gold, minion.qn+'_t', 1, 1, 1, minion.archetype)
                    if token > 0:
                        self.execute_passive_play(minion_token)
                        self.execute_passive_play(minion_token)
                    else:
                        self.execute_passive_play(minion_token)
                    self.board.insert(direction+token_place-1, minion_token)
                    if token_place % 3 == 0:
                        token_place = 0
                    if not minion_token.gold:
                        if minion_token.name in self.double:
                            if self.double[minion_token.name] == 2:
                                self.timing_IA()
                                self.triple_minion(minion_token, is_token=True)
                                self.double.pop(minion_token.name)
                            else:
                                self.double[minion_token.name] += 1
                        else:
                            self.double[minion_token.name] = 1

def btc_buff_one_minion(self, minion, target, buff, direction, isHuman):
    all_target = self.board_position_of(target, minion)
    self.timing_IA()
    if all_target:
        pos = self.get_answer_battlecry(all_target) if isHuman else choice(all_target)-1
        n = 2 if minion.gold else 1
        for _ in range(self.brann):
            self.board[pos].atk += buff*n
            self.board[pos].hp += buff*n
        if direction < len(self.board)//2:
            pos -= 1
        # return (self.buff_minion, pos+2, len(self.board)+1)

def btc_houndMaster(self, minion, target, buff, direction, isHuman):
    all_target = self.board_position_of(target, minion)
    self.timing_IA()
    if all_target:
        for _ in range(self.brann):
            n = 2 if minion.gold else 1
            pos = self.get_answer_battlecry(all_target) if isHuman else choice(all_target)-1
            self.board[pos].taunt = True
            self.board[pos].atk += buff*n
            self.board[pos].hp += buff*n
            if direction < len(self.board)//2:
                pos -= 1
        # return (self.buff_minion, pos+2, len(self.board)+1)

def btc_deckSwabbie(self, minion, target, buff, direction, isHuman):
    n = 2 if minion.gold else 1
    for _ in range(self.brann):
        if self.up_cost[0] != 'M':
            self.up_cost[0] -= 1*n

def btc_pogoHopper(self, minion, target, buff, direction, isHuman):
    n = 2 if minion.gold else 1
    for _ in range(self.brann):
        minion.atk += buff*n * self.n_pogo
        minion.hp += buff*n * self.n_pogo
    self.n_pogo += 1

def btc_buff_random_minion(self, minion, target, buff, direction, isHuman):
    for _ in range(self.brann):
        for archetype in target:
            all_target = self.board_position_of(archetype, minion)
            if all_target:
                n = 2 if minion.gold else 1
                pos = choice(all_target)-1
                self.board[pos].atk += buff*n
                self.board[pos].hp += buff*n
                
def btc_buff_atk_all_minion(self, minion, target, buff, direction, isHuman):
    all_target = self.board_position_of(target, minion)
    if all_target:
        for _ in range(self.brann):
            n = 2 if minion.gold else 1
            for pos in all_target:
                self.board[pos-1].atk += buff*n

def btc_buff_hp_all_minion(self, minion, target, buff, direction, isHuman):
    all_target = self.board_position_of(target, minion)
    if all_target:
        for _ in range(self.brann):
            n = 2 if minion.gold else 1
            for pos in all_target:
                self.board[pos-1].hp += buff*n

def btc_buff_all_minion(self, minion, target, buff, direction, isHuman):
    btc_buff_hp_all_minion(self, minion, target, buff, direction, isHuman)
    btc_buff_atk_all_minion(self, minion, target, buff, direction, isHuman)

def btc_defenderOfArgus(self, minion, target, buff, direction, isHuman):
    n = 2 if minion.gold else 1
    if len(self.board) > 1:
        for _ in range(self.brann):
            if direction == 1:
                self.board[direction].taunt = True
                self.board[direction].atk += 1*n
                self.board[direction].hp += 1*n
            elif direction == len(self.board):
                self.board[direction-2].taunt = True
                self.board[direction-2].atk += 1*n
                self.board[direction-2].hp += 1*n
            else:
                for i in range(0,3,2):
                    self.board[direction-i].taunt = True
                    self.board[direction-i].atk += 1*n
                    self.board[direction-i].hp += 1*n

def btc_southseaStrongarm(self, minion, target, buff, direction, isHuman):
    btc_buff_one_minion(self, minion, target, buff*self.n_pirate, direction, isHuman)

def btc_toxfin(self, minion, target, buff, direction, isHuman):
    all_target = self.board_position_of(target)
    if all_target:
        pos = self.get_answer_battlecry(all_target) if isHuman else choice(all_target)-1
        self.board[pos].poisonous = True
        if direction < len(self.board)//2:
            pos -= 1
        # return (self.buff_minion, pos+2, len(self.board)+1)

def btc_annihilanBattlemaster(self, minion, target, buff, direction, isHuman):
    n = 2 if minion.gold else 1
    for _ in range(self.brann):
        minion.hp += (self.max_hp - self.hp) * (buff*n)

def btc_vulgarHomunculus(self, minion, target, buff, direction, isHuman):
    for _ in range(self.brann):
        self.hp -= 2

def btc_murozond(self, minion, target, buff, direction, isHuman):
    pass

def btc_gentleMegasaur(self, minion, target, buff, direction, isHuman):
    all_target = self.board_position_of(target, minion)
    if len(all_target) > 0:
        discovery = self.get_discovery(minion=minion)
        n = 2 if minion.gold else 1
        for _ in range(self.brann):
            for i in range(n):
                self.view_discover = discovery.display_discovery()
                target_discovery = self.get_answer_discovery() if isHuman else choice([1,2,3])
                name_buff = discovery.cards_discover[target_discovery-1]
                if name_buff == 'crackling':
                    for pos in all_target:
                        self.board[pos-1].shield = True
                elif name_buff == 'flaming':
                    for pos in all_target:
                        self.board[pos-1].atk += 3
                elif name_buff == 'spores':
                    for pos in all_target:
                        self.board[pos-1].deathrattle = True
                elif name_buff == 'poison':
                    for pos in all_target:
                        self.board[pos-1].poisonous = True
                elif name_buff == 'massive':
                    for pos in all_target:
                        self.board[pos-1].taunt = True
                elif name_buff == 'volcanic':
                    for pos in all_target:
                        self.board[pos-1].atk += 1
                        self.board[pos-1].hp += 1
                elif name_buff == 'lightning':
                    for pos in all_target:
                        self.board[pos-1].windfury = True
                else:
                    for pos in all_target:
                        self.board[pos-1].hp += 3
        self.view_discover = ''

def btc_primalfinLookout(self, minion, target, buff, direction, isHuman):
    if len(self.board_position_of('murloc')) > 1:
        discovery = self.get_discovery(minion=minion)
        self.view_discover = discovery.display_discovery()
        n = 2 if minion.gold else 1
        for _ in range(self.brann):
            for i in range(n):
                self.timing_IA()
                target_discovery = self.get_answer_discovery() if isHuman else choice([1,2,3])
                new_minion = discovery.cards_discover[target_discovery-1]
                new_minion = self.create_minion(False, new_minion)
                self.hand.append(new_minion)
                if new_minion.name in self.double and not new_minion.gold:
                    if self.double[new_minion.name] == 2:
                        self.triple_minion(new_minion, is_token=False)
                        self.double.pop(new_minion.name)
                    else:
                        self.double[new_minion.name] += 1
                else:
                    self.double[new_minion.name] = 1
        self.view_discover = ''

def pas_microMachine(self, minion, target, buff):
	n = 2 if minion.gold else 1
	minion.atk += 1*n

def pas_hangryDragon(self, minion, target, buff):
	if self.is_win_fight:
		n = 2 if minion.gold else 1
		minion.atk += 2*n
		minion.hp += 2*n

def pas_shifterZerus(self, minion, target, buff):
    random_minion = choice(list(MINIONS))
    gold = True if minion.gold else False
    minion = Minion(random_minion, gold, *[value for value in MINIONS[random_minion].values()][1:])
    minion.name  = 'shifterZerus'
    minion.qn = "Z{}Z".format(minion.qn)
    minion.passive = MINIONS['shifterZerus']['passive']
    minion.true_name = random_minion
    return minion
   

# at 'end_turn'
def pas_razorgoreTheUntamed(self, minion, target, buff):
	n_dragon = self.board_position_of(target)
	if n_dragon:
		n = 2 if minion.gold else 1
		minion.atk += len(n_dragon)*n
		minion.hp += len(n_dragon)*n

def pas_cobaltScalebane(self, minion, target, buff):
    all_target = self.board_position_of()
    if len(all_target) > 1:
        n = 2 if minion.gold else 1
        all_target.remove(int([pos+1 for (pos, m) in enumerate(self.board) if m.id == minion.id][0]))
        pos = choice(all_target)
        self.board[pos-1].atk += buff*n

def pas_ironSensei(self, minion, target, buff):
    all_target = self.board_position_of('meca')
    if len(all_target) > 1:
        n = 2 if minion.gold else 1
        all_target.remove(int([pos+1 for (pos, m) in enumerate(self.board) if m.id == minion.id][0]))
        pos = choice(all_target)
        self.board[pos-1].atk += buff*n
        self.board[pos-1].hp += buff*n

def pas_lightfangEnforcer(self, minion, target, buff):
    for archetype in ('murloc', 'dragon', 'beast', 'demon', 'pirate', 'meca'):
        all_target = self.board_position_of(archetype)
        if all_target:
            n = 2 if minion.gold else 1
            pos = choice(all_target)
            self.board[pos-1].atk += buff*n
            self.board[pos-1].hp += buff//2*n

def pas_goldgrubber(self, minion, target, buff):
    if self.board_gold_minion:
        n = 2 if minion.gold else 1
        self.board_gold_minion += 1 if minion.gold else 0
        minion.atk += buff*n*self.board_gold_minion
        minion.hp += buff*n*self.board_gold_minion

# when 'play' minion
def pas_wrathWeaver_saltyLooter_crowdFavorite_rabidSaurolisk(self, minion, minion_play, target, buff):
    n = 2 if minion.gold else 1
    minion.atk += buff*n
    minion.hp += buff*n
    if not self.immunity and minion.name == 'wrathWeaver':
        self.hp -= 1
        if self.watcher:
            for minion in self.board:
                if minion.name == 'floatingWatcher':
                    fc, target, buff = list(minion.passive.values())[:-1]
                    fc(self, minion, target, buff)

def pas_kalecgosArcaneAspect(self, minion, minion_play, target, buff):
    n_dragon = self.board_position_of('dragon')
    n = 2 if minion.gold else 1
    for pos in n_dragon:
        self.board[pos-1].atk += buff*n
        self.board[pos-1].hp += buff*n
    if minion_play.archetype == 'dragon':
        minion_play.atk += buff*n
        minion_play.hp += buff*n

def pas_murlocTidecaller(self, minion, minion_play, target, buff):
    n = 2 if minion.gold else 1
    minion.atk += buff*n

def pas_packLeader(self, minion, minion_play, target, buff):
    n = 2 if minion.gold else 1
    minion_play.atk += buff*n

def pas_mamaBear(self, minion, minion_play, target, buff):
    n = 2 if minion.gold else 1
    minion_play.atk += buff*n
    minion_play.hp += buff*n

def pas_floatingWatcher(self, minion, target, buff):
    n = 2 if minion.gold else 1
    minion.atk += buff*n
    minion.hp += buff*n



# when 'sold' minion
def pas_stewardOfTime(self, minion, target, buff):
    n = 2 if minion.gold else 1
    for minion in self.shop:
        minion.atk += buff*n
        minion.hp += buff*n

def pas_freedealingGambler(self, minion, target, buff):
    n = 2 if minion.gold else 1
    self.gold += (buff*n-1)
    self.gold = 10 if self.gold > 10 else self.gold

# when 'present' minion
def pas_murlocWarleader_southseaCaptain_malGanis_siegeBreaker(self, minion, minion_play, target, buff, action):
    all_target = self.board_position_of(target)
    n = 2 if minion.gold else 1
    if action == 'play':
        all_target.remove(int([pos+1 for (pos, m) in enumerate(self.board) if m.id == minion.id][0]))
        if minion.n_passive == 0:
            minion.n_passive += 1
            if minion.name == 'malGanis':
                self.immunity += 1
            for pos in all_target:
                self.board[pos-1].atk += buff*n
                if minion.name == 'southseaCaptain' or minion.name == 'malGanis':
                    self.board[pos-1].hp += buff*n
        elif minion.n_passive >= 1:
            if minion_play.archetype == target:
                minion_play.atk += buff*n 
                if minion.name == 'southseaCaptain' or minion.name == 'malGanis':
                    minion_play.hp += buff*n
    else:
        if minion.name == 'malGanis':
            self.immunity -= 1
        if len(all_target) > 1:
            for pos in all_target:
                self.board[pos-1].atk -= buff*n
                if minion.name == 'southseaCaptain' or minion.name == 'malGanis':
                    self.board[pos-1].hp -= buff*n

def pas_oldMurkEye(self, minion, minion_play, target, buff, action=False):
    n = 2 if minion.gold else 1
    all_target = self.board_position_of(target)
    if action == 'play':
        if minion.n_passive == 0:
            self.oldmurloc += 1
        minion.n_passive += 1
        minion.atk = (len(all_target)-1)*n + (2*n)
    elif action == 'sold':
        self.oldmurloc -= 1


# when buy
def pas_capnHoggarr(self, minion, minion_play, target, buff, action):
    n = 2 if minion.gold else 1
    if action == 'play':
        self.gold += buff*n
    elif action == 'sold':
        self.hoggarr -= 1

MINIONS = {
    'dreadAdmiralEliza': {
		'gold': False,
		'qn': 'Eliza',
		'atk': 6,
		'hp': 7,
		'lvl': 6, 
        'archetype':'pirate',
		'legendary': True,
		'img': './img/minion6/dreadAdmiralEliza.png',
		'img_discovery': './img/discovery_minion6/dreadAdmiralEliza.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'gentleMegasaur': {
		'gold': False,
		'qn': 'Megasaur',
		'atk': 5,
		'hp': 4,
		'lvl': 6,
		'archetype': 'beast',
		'legendary': False,
		'img': './img/minion6/gentleMegasaur.png',
		'img_discovery': './img/discovery_minion6/gentleMegasaur.png',
		'battlecry': {
            'fc': btc_gentleMegasaur,
            'target': 'murloc',
            'buff': 1,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'ghastcoiler': {
		'gold': False,
		'qn': 'Coiler',
		'atk': 7,
		'hp': 7,
		'lvl': 6,
		'archetype': 'beast',
		'legendary': False,
		'img': './img/minion6/ghastcoiler.png',
		'img_discovery': './img/discovery_minion6/ghastcoiler.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'theTideRazor': {
		'gold': False,
		'qn': 'Razor',
		'atk': 6,
		'hp': 4,
		'lvl': 6,
		'archetype': 'neutral',
		'legendary': False,
		'img': './img/minion6/theTideRazor.png',
		'img_discovery': './img/discovery_minion6/theTideRazor.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'zappSlywick': {
		'gold': False,
		'qn': 'Zapp',
		'atk': 7,
		'hp': 10,
		'lvl': 6,
		'archetype': 'neutral',
		'legendary': True,
		'img': './img/minion6/zappSlywick.png',
		'img_discovery': './img/discovery_minion6/zappSlywick.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': True,
	},
    'foeReaper4000': {
		'gold': False,
		'qn': 'Reaper',
		'atk': 6,
		'hp': 9,
		'lvl': 6,
		'archetype': 'meca',
		'legendary': True,
		'img': './img/minion6/foeReaper4000.png',
		'img_discovery': './img/discovery_minion6/foeReaper4000.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'kalecgosArcaneAspect': {
		'gold': False,
		'qn': 'Kalecgos',
		'atk': 4,
		'hp': 12,
		'lvl': 6,
		'archetype': 'dragon',
		'legendary': True,
		'img': './img/minion6/kalecgosArcaneAspect.png',
		'img_discovery': './img/discovery_minion6/kalecgosArcaneAspect.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': {
			'fc': pas_kalecgosArcaneAspect,
			'target': 'battlecry',
			'buff': 1,
			'trigger': 'play',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'mamaBear': {
		'gold': False,
		'qn': 'Mamabear',
		'atk': 5,
		'hp': 5,
		'lvl': 6,
		'archetype': 'beast',
		'legendary': False,
		'img': './img/minion6/mamaBear.png',
		'img_discovery': './img/discovery_minion6/mamaBear.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': {
			'fc': pas_mamaBear,
			'target': 'beast',
			'buff': 5,
			'trigger': 'play',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'maexxna': {
		'gold': False,
		'qn': 'Maexxna',
		'atk': 2,
		'hp': 8,
		'lvl': 6,
		'archetype': 'beast',
		'legendary': True,
		'img': './img/minion6/maexxna.png',
		'img_discovery': './img/discovery_minion6/maexxna.png',
		'battlecry': False,
		'poisonous': True,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'kangorsApprentice': {
		'gold': False,
		'qn': 'Kangor',
		'atk': 3,
		'hp': 6,
		'lvl': 6,
		'archetype': 'neutral',
		'legendary': False,
		'img': './img/minion6/kangorsApprentice.png',
		'img_discovery': './img/discovery_minion6/kangorsApprentice.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'nadinaTheRed': {
		'gold': False,
		'qn': 'Nadina',
		'atk': 7,
		'hp': 4,
		'lvl': 6,
		'archetype': 'neutral',
		'legendary': True,
		'img': './img/minion6/nadinaTheRed.png',
		'img_discovery': './img/discovery_minion6/nadinaTheRed.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'impMama': {
		'gold': False,
		'qn': 'ImpMama',
		'atk': 6,
		'hp': 10,
		'lvl': 6,
		'archetype': 'demon',
		'legendary': False,
		'img': './img/minion6/impMama.png',
		'img_discovery': './img/discovery_minion6/impMama.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    #TIER 5
    'annihilanBattlemaster': {
		'gold': False,
		'qn': 'BattleMaster',
		'atk': 3,
		'hp': 1,
		'lvl': 5,
		'archetype': 'demon',
		'legendary': False,
		'img': './img/minion5/AnnihilanBattlemaster.png',
		'img_discovery': './img/discovery_minion5/AnnihilanBattlemaster.png',
		'battlecry': {
            'fc': btc_annihilanBattlemaster,
            'target': None,
            'buff': 1,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'baronRivendare': {
		'gold': False,
		'qn': 'Baron',
		'atk': 1,
		'hp': 7,
		'lvl': 5,
		'archetype': 'neutral',
		'legendary': True,
		'img': './img/minion5/baronRivendare.png',
		'img_discovery': './img/discovery_minion5/baronRivendare.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'brannBronzebeard': {
		'gold': False,
		'qn': 'Brann',
		'atk': 2,
		'hp': 4,
		'lvl': 5,
		'archetype': 'neutral',
		'legendary': True,
		'img': './img/minion5/brannBronzebeard.png',
		'img_discovery': './img/discovery_minion5/brannBronzebeard.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'capnHoggarr': {
		'gold': False,
		'qn': 'Hoggarr',
		'atk': 6,
		'hp': 6,
		'lvl': 5,
		'archetype': 'pirate',
		'legendary': True,
		'img': './img/minion5/capnHoggarr.png',
		'img_discovery': './img/discovery_minion5/capnHoggarr.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': {
			'fc': pas_capnHoggarr,
			'target': 'pirate',
			'buff': 1,
			'trigger': 'buy',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'goldrinnTheGreatWolf': {
		'gold': False,
		'qn': 'Goldrinn',
		'atk': 4,
		'hp': 4,
		'lvl': 5,
		'archetype': 'beast',
		'legendary': True,
		'img': './img/minion5/goldrinnTheGreatWolf.png',
		'img_discovery': './img/discovery_minion5/goldrinnTheGreatWolf.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'ironhideDirehorn': {
		'gold': False,
		'qn': 'Ironhide',
		'atk': 7,
		'hp': 7,
		'lvl': 5,
		'archetype': 'beast',
		'legendary': False,
		'img': './img/minion5/ironhideDirehorn.png',
		'img_discovery': './img/discovery_minion5/ironhideDirehorn.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': True,
		'cleave': False,
		'windfury': False,
	},
    'junkbot': {
		'gold': False,
		'qn': 'Junkbot',
		'atk': 1,
		'hp': 5,
		'lvl': 5,
		'archetype': 'meca',
		'legendary': False,
		'img': './img/minion5/junkbot.png',
		'img_discovery': './img/discovery_minion5/junkbot.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'kingBagurgle': {
		'gold': False,
		'qn': 'Bagurgle',
		'atk': 6,
		'hp': 3,
		'lvl': 5,
		'archetype': 'murloc',
		'legendary': True,
		'img': './img/minion5/kingBagurgle.png',
		'img_discovery': './img/discovery_minion5/kingBagurgle.png',
		'battlecry': {
            'fc': btc_buff_all_minion,
            'target': 'murloc',
            'buff': 2,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'lightfangEnforcer': {
		'gold': False,
		'qn': 'Lightfang',
		'atk': 2,
		'hp': 2,
		'lvl': 5,
		'archetype': 'neutral',
		'legendary': False,
		'img': './img/minion5/lightfangEnforcer.png',
		'img_discovery': './img/discovery_minion5/lightfangEnforcer.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': {
			'fc': pas_lightfangEnforcer,
			'target': 'all',
			'buff': 2,
			'trigger': 'end_turn',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'malGanis': {
		'gold': False,
		'qn': 'Mal\'Ganis',
		'atk': 9,
		'hp': 7,
		'lvl': 5,
		'archetype': 'demon',
		'legendary': True,
		'img': './img/minion5/malGanis.png',
		'img_discovery': './img/discovery_minion5/malGanis.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': {
			'fc': pas_murlocWarleader_southseaCaptain_malGanis_siegeBreaker,
			'target': 'demon',
			'buff': 2,
			'trigger': 'present',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'murozond': {
		'gold': False,
		'qn': 'Murozond',
		'atk': 5,
		'hp': 5,
		'lvl': 5,
		'archetype': 'dragon',
		'legendary': True,
		'img': './img/minion5/murozond.png',
		'img_discovery': './img/discovery_minion5/murozond.png',
		'battlecry': {
            'fc': btc_murozond,
            'target': None,
            'buff': None,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'natPagleExtremeAngler': {
		'gold': False,
		'qn': 'Nat Pagle',
		'atk': 8,
		'hp': 5,
		'lvl': 5,
		'archetype': 'pirate',
		'legendary': True,
		'img': './img/minion5/natPagleExtremeAngler.png',
		'img_discovery': './img/discovery_minion5/natPagleExtremeAngler.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': True,
		'cleave': False,
		'windfury': False,
	},
    'primalfinLookout': {
		'gold': False,
		'qn': 'Primalfin',
		'atk': 3,
		'hp': 2,
		'lvl': 5,
		'archetype': 'murloc',
		'legendary': False,
		'img': './img/minion5/primalfinLookout.png',
		'img_discovery': './img/discovery_minion5/primalfinLookout.png',
		'battlecry': {
            'fc': btc_primalfinLookout,
            'target': 'murloc',
            'buff': None,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'razorgoreTheUntamed': {
		'gold': False,
		'qn': 'Razorgore',
		'atk': 2,
		'hp': 4,
		'lvl': 5,
		'archetype': 'dragon',
		'legendary': True,
		'img': './img/minion5/razorgoreTheUntamed.png',
		'img_discovery': './img/discovery_minion5/razorgoreTheUntamed.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': {
			'fc': pas_razorgoreTheUntamed,
			'target': 'dragon',
			'buff': 1,
			'trigger': 'end_turn',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'seabreakerGoliath': {
		'gold': False,
		'qn': 'Goliath',
		'atk': 6,
		'hp': 7,
		'lvl': 5,
		'archetype': 'pirate',
		'legendary': False,
		'img': './img/minion5/seabreakerGoliath.png',
		'img_discovery': './img/discovery_minion5/seabreakerGoliath.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': True,
		'cleave': False,
		'windfury': True,
	},
    'sneedsOldShredder': {
		'gold': False,
		'qn': 'Sneed',
		'atk': 5,
		'hp': 7,
		'lvl': 5,
		'archetype': 'meca',
		'legendary': True,
		'img': './img/minion5/sneedsOldShredder.png',
		'img_discovery': './img/discovery_minion5/sneedsOldShredder.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'strongshellScavenger': {
		'gold': False,
		'qn': 'Strongshell',
		'atk': 2,
		'hp': 3,
		'lvl': 5,
		'archetype': 'neutral',
		'legendary': False,
		'img': './img/minion5/strongshellScavenger.png',
		'img_discovery': './img/discovery_minion5/strongshellScavenger.png',
		'battlecry': {
            'fc': btc_buff_all_minion,
            'target': 'taunt',
            'buff': 2,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'voidlord': {
		'gold': False,
		'qn': 'Voidlord',
		'atk': 3,
		'hp': 9,
		'lvl': 5,
		'archetype': 'demon',
		'legendary': False,
		'img': './img/minion5/voidlord.png',
		'img_discovery': './img/discovery_minion5/voidlord.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': True,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    # TIER 4
    'annoyOModule': {
		'gold': False,
		'qn': 'Annoy-Module',
		'atk': 2,
		'hp': 4,
		'lvl': 4,
		'archetype': 'meca',
		'legendary': False,
		'img': './img/minion4/annoyOModule.png',
		'img_discovery': './img/discovery_minion4/annoyOModule.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': True,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': True,
		'reborn': False,
		'magnetic': True,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'bolvarFireblood': {
		'gold': False,
		'qn': 'Bolvar',
		'atk': 1,
		'hp': 7,
		'lvl': 4,
		'archetype': 'neutral',
		'legendary': True,
		'img': './img/minion4/bolvarFireblood.png',
		'img_discovery': './img/discovery_minion4/bolvarFireblood.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': True,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'caveHydra': {
		'gold': False,
		'qn': 'Hydra',
		'atk': 2,
		'hp': 4,
		'lvl': 4,
		'archetype': 'beast',
		'legendary': False,
		'img': './img/minion4/caveHydra.png',
		'img_discovery': './img/discovery_minion4/caveHydra.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': True,
		'windfury': False,
	},
    'cobaltScalebane': {
		'gold': False,
		'qn': 'Cobalt',
		'atk': 5,
		'hp': 5,
		'lvl': 4,
		'archetype': 'dragon',
		'legendary': False,
		'img': './img/minion4/cobaltScalebane.png',
		'img_discovery': './img/discovery_minion4/cobaltScalebane.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': {
			'fc': pas_cobaltScalebane,
			'target': None,
			'buff': 3,
			'trigger': 'end_turn',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'defenderOfArgus': {
		'gold': False,
		'qn': 'Argus',
		'atk': 2,
		'hp': 3,
		'lvl': 4,
		'archetype': 'neutral',
		'legendary': False,
		'img': './img/minion4/defenderOfArgus.png',
		'img_discovery': './img/discovery_minion4/defenderOfArgus.png',
		'battlecry': {
            'fc': btc_defenderOfArgus,
            'target': None,
            'buff': 1,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'drakonidEnforcer': {
		'gold': False,
		'qn': 'Drakonid',
		'atk': 3,
		'hp': 6,
		'lvl': 4,
		'archetype': 'dragon',
		'legendary': False,
		'img': './img/minion4/drakonidEnforcer.png',
		'img_discovery': './img/discovery_minion4/drakonidEnforcer.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'floatingWatcher': {
		'gold': False,
		'qn': 'Watcher',
		'atk': 4,
		'hp': 4,
		'lvl': 4,
		'archetype': 'demon',
		'legendary': False,
		'img': './img/minion4/floatingWatcher.png',
		'img_discovery': './img/discovery_minion4/floatingWatcher.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': {
			'fc': pas_floatingWatcher,
			'target': None,
			'buff': 2,
			'trigger': 'play',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'goldgrubber': {
		'gold': False,
		'qn': 'Goldgrubber',
		'atk': 2,
		'hp': 2,
		'lvl': 4,
		'archetype': 'pirate',
		'legendary': False,
		'img': './img/minion4/goldgrubber.png',
		'img_discovery': './img/discovery_minion4/goldgrubber.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': {
			'fc': pas_goldgrubber,
			'target': None,
			'buff': 2,
			'trigger': 'end_turn',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'heraldOfFlame': {
		'gold': False,
		'qn': 'Herald',
		'atk': 5,
		'hp': 6,
		'lvl': 4,
		'archetype': 'dragon',
		'legendary': False,
		'img': './img/minion4/heraldOfFlame.png',
		'img_discovery': './img/discovery_minion4/heraldOfFlame.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': True,
		'cleave': False,
		'windfury': False,
	},
    'ironSensei': {
		'gold': False,
		'qn': 'Sensei',
		'atk': 2,
		'hp': 2,
		'lvl': 4,
		'archetype': 'meca',
		'legendary': False,
		'img': './img/minion4/ironSensei.png',
		'img_discovery': './img/discovery_minion4/ironSensei.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': {
			'fc': pas_ironSensei,
			'target': 'meca',
			'buff': 2,
			'trigger': 'end_turn',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'mechanoEgg': {
		'gold': False,
		'qn': 'Mechano-Egg',
		'atk': 0,
		'hp': 5,
		'lvl': 4,
		'archetype': 'meca',
		'legendary': False,
		'img': './img/minion4/mechanoEgg.png',
		'img_discovery': './img/discovery_minion4/mechanoEgg.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'menagerieMagician': {
		'gold': False,
		'qn': 'Menagerie',
		'atk': 4,
		'hp': 4,
		'lvl': 4,
		'archetype': 'neutral',
		'legendary': False,
		'img': './img/minion4/menagerieMagician.png',
		'img_discovery': './img/discovery_minion4/menagerieMagician.png',
		'battlecry': {
            'fc': btc_buff_random_minion,
            'target': ('dragon', 'beast', 'murloc'),
            'buff': 2,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'ripsnarlCaptain': {
		'gold': False,
		'qn': 'Ripsnarl',
		'atk': 3,
		'hp': 4,
		'lvl': 4,
		'archetype': 'pirate',
		'legendary': False,
		'img': './img/minion4/ripsnarlCaptain.png',
		'img_discovery': './img/discovery_minion4/ripsnarlCaptain.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'savannahHighmane': {
		'gold': False,
		'qn': 'Savannah',
		'atk': 6,
		'hp': 5,
		'lvl': 4,
		'archetype': 'beast',
		'legendary': False,
		'img': './img/minion4/savannahHighmane.png',
		'img_discovery': './img/discovery_minion4/savannahHighmane.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'securityRover': {
		'gold': False,
		'qn': 'Rover',
		'atk': 2,
		'hp': 6,
		'lvl': 4,
		'archetype': 'meca',
		'legendary': False,
		'img': './img/minion4/securityRover.png',
		'img_discovery': './img/discovery_minion4/securityRover.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'siegeBreaker': {
		'gold': False,
		'qn': 'Siegebreaker',
		'atk': 5,
		'hp': 8,
		'lvl': 4,
		'archetype': 'demon',
		'legendary': False,
		'img': './img/minion4/siegeBreaker.png',
		'img_discovery': './img/discovery_minion4/siegeBreaker.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': True,
		'passive': {
			'fc': pas_murlocWarleader_southseaCaptain_malGanis_siegeBreaker,
			'target': 'demon',
			'buff': 1,
			'trigger': 'present',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'southseaStrongarm': {
		'gold': False,
		'qn': 'Strongarm',
		'atk': 5,
		'hp': 4,
		'lvl': 4,
		'archetype': 'pirate',
		'legendary': False,
		'img': './img/minion4/southseaStrongarm.png',
		'img_discovery': './img/discovery_minion4/southseaStrongarm.png',
		'battlecry': {
            'fc': btc_southseaStrongarm,
            'target': 'pirate',
            'buff': 1,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'toxfin': {
		'gold': False,
		'qn': 'Toxfin',
		'atk': 1,
		'hp': 2,
		'lvl': 4,
		'archetype': 'murloc',
		'legendary': False,
		'img': './img/minion4/toxfin.png',
		'img_discovery': './img/discovery_minion4/toxfin.png',
		'battlecry': {
            'fc': btc_toxfin,
            'target': 'murloc',
            'buff': None,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'virmenSensei': {
		'gold': False,
		'qn': 'Virmen',
		'atk': 4,
		'hp': 5,
		'lvl': 4,
		'archetype': 'neutral',
		'legendary': False,
		'img': './img/minion4/virmenSensei.png',
		'img_discovery': './img/discovery_minion4/virmenSensei.png',
		'battlecry': {
            'fc': btc_buff_one_minion,
            'target': 'beast',
            'buff': 2,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    # TIER 3
    'bloodsailCannoneer': {
		'gold': False,
		'qn': 'Cannoneer',
		'atk': 4,
		'hp': 2,
		'lvl': 3,
		'archetype': 'pirate',
		'legendary': False,
		'img': './img/minion3/bloodsailCannoneer.png',
		'img_discovery': './img/discovery_minion3/bloodsailCannoneer.png',
		'battlecry': {
            'fc': btc_buff_atk_all_minion,
            'target': 'pirate',
            'buff': 3,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'bronzeWarden': {
		'gold': False,
		'qn': 'Bronze',
		'atk': 2,
		'hp': 1,
		'lvl': 3,
		'archetype': 'dragon',
		'legendary': False,
		'img': './img/minion3/bronzeWarden.png',
		'img_discovery': './img/discovery_minion3/bronzeWarden.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': True,
		'reborn': True,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'coldlightSeer': {
		'gold': False,
		'qn': 'Coldlight',
		'atk': 2,
		'hp': 3,
		'lvl': 3,
		'archetype': 'murloc',
		'legendary': False,
		'img': './img/minion3/coldlightSeer.png',
		'img_discovery': './img/discovery_minion3/coldlightSeer.png',
		'battlecry': {
            'fc': btc_buff_hp_all_minion,
            'target': 'murloc',
            'buff': 2,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'crowdFavorite': {
		'gold': False,
		'qn': 'Favorite',
		'atk': 4,
		'hp': 4,
		'lvl': 3,
		'archetype': 'neutral',
		'legendary': False,
		'img': './img/minion3/crowdFavorite.png',
		'img_discovery': './img/discovery_minion3/crowdFavorite.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': {
			'fc': pas_wrathWeaver_saltyLooter_crowdFavorite_rabidSaurolisk,
			'target': 'battlecry',
			'buff': 1,
			'trigger': 'play',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'crystalweaver': {
		'gold': False,
		'qn': 'Crystal',
		'atk': 5,
		'hp': 4,
		'lvl': 3,
		'archetype': 'neutral',
		'legendary': False,
		'img': './img/minion3/crystalweaver.png',
		'img_discovery': './img/discovery_minion3/crystalweaver.png',
		'battlecry': {
            'fc': btc_buff_all_minion,
            'target': 'demon',
            'buff': 1,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'deflectOBot': {
		'gold': False,
		'qn': 'Deflect-o-Bot',
		'atk': 3,
		'hp': 2,
		'lvl': 3,
		'archetype': 'meca',
		'legendary': False,
		'img': './img/minion3/deflectOBot.png',
		'img_discovery': './img/discovery_minion3/deflectOBot.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': True,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'felfinNavigator': {
		'gold': False,
		'qn': 'Navigator',
		'atk': 4,
		'hp': 4,
		'lvl': 3,
		'archetype': 'murloc',
		'legendary': False,
		'img': './img/minion3/felfinNavigator.png',
		'img_discovery': './img/discovery_minion3/felfinNavigator.png',
		'battlecry': {
            'fc': btc_buff_all_minion,
            'target': 'murloc',
            'buff': 1,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'hangryDragon': {
		'gold': False,
		'qn': 'Hangry',
		'atk': 4,
		'hp': 4,
		'lvl': 3,
		'archetype': 'dragon',
		'legendary': False,
		'img': './img/minion3/hangryDragon.png',
		'img_discovery': './img/discovery_minion3/hangryDragon.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': {
			'fc': pas_hangryDragon,
			'target': None,
			'buff': 2,
			'trigger': 'start_turn',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'houndMaster': {
		'gold': False,
		'qn': 'Houndmaster',
		'atk': 4,
		'hp': 3,
		'lvl': 3,
		'archetype': 'neutral',
		'legendary': False,
		'img': './img/minion3/houndMaster.png',
		'img_discovery': './img/discovery_minion3/houndMaster.png',
		'battlecry': {
            'fc': btc_houndMaster,
            'target': 'beast',
            'buff': 2,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'impGangBoss': {
		'gold': False,
		'qn': 'Gang Boss',
		'atk': 2,
		'hp': 4,
		'lvl': 3,
		'archetype': 'demon',
		'legendary': False,
		'img': './img/minion3/impGangBoss.png',
		'img_discovery': './img/discovery_minion3/impGangBoss.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'infestedWolf': {
		'gold': False,
		'qn': 'Wolf',
		'atk': 3,
		'hp': 3,
		'lvl': 3,
		'archetype': 'beast',
		'legendary': False,
		'img': './img/minion3/infestedWolf.png',
		'img_discovery': './img/discovery_minion3/infestedWolf.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'khadgar': {
		'gold': False,
		'qn': 'Khadgar',
		'atk': 2,
		'hp': 2,
		'lvl': 3,
		'archetype': 'neutral',
		'legendary': True,
		'img': './img/minion3/khadgar.png',
		'img_discovery': './img/discovery_minion3/khadgar.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'monstrousMacaw': {
		'gold': False,
		'qn': 'Macaw',
		'atk': 3,
		'hp':2,
		'lvl': 3,
		'archetype': 'beast',
		'legendary': False,
		'img': './img/minion2/monstrousMacaw.png',
		'img_discovery': './img/discovery_minion2/monstrousMacaw.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'packLeader': {
		'gold': False,
		'qn': 'Leader',
		'atk': 3,
		'hp': 3,
		'lvl': 3,
		'archetype': 'neutral',
		'legendary': False,
		'img': './img/minion3/packLeader.png',
		'img_discovery': './img/discovery_minion3/packLeader.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': {
			'fc': pas_packLeader,
			'target': 'beast',
			'buff': 3,
			'trigger': 'play',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'pilotedShredder': {
		'gold': False,
		'qn': 'Shredder',
		'atk': 4,
		'hp': 3,
		'lvl': 3,
		'archetype': 'meca',
		'legendary': False,
		'img': './img/minion3/pilotedShredder.png',
		'img_discovery': './img/discovery_minion3/pilotedShredder.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'replicatingMenace': {
		'gold': False,
		'qn': 'Menace',
		'atk': 3,
		'hp': 1,
		'lvl': 3,
		'archetype': 'meca',
		'legendary': False,
		'img': './img/minion3/replicatingMenace.png',
		'img_discovery': './img/discovery_minion3/replicatingMenace.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': True,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'saltyLooter': {
		'gold': False,
		'qn': 'Looter',
		'atk': 3,
		'hp': 3,
		'lvl': 3,
		'archetype': 'pirate',
		'legendary': False,
		'img': './img/minion3/saltyLooter.png',
		'img_discovery': './img/discovery_minion3/saltyLooter.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': {
			'fc': pas_wrathWeaver_saltyLooter_crowdFavorite_rabidSaurolisk,
			'target': 'pirate',
			'buff': 1,
			'trigger': 'play',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'screwjankClunker': {
		'gold': False,
		'qn': 'Clunker',
		'atk': 2,
		'hp': 5,
		'lvl': 3,
		'archetype': 'meca',
		'legendary': False,
		'img': './img/minion3/screwjankClunker.png',
		'img_discovery': './img/discovery_minion3/screwjankClunker.png',
		'battlecry': {
            'fc': btc_buff_one_minion,
            'target': 'meca',
            'buff': 2,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'shifterZerus': {
		'gold': False,
		'qn': 'Zerus',
		'atk': 1,
		'hp': 1,
		'lvl': 3,
		'archetype': 'neutral',
		'legendary': True,
		'img': './img/minion3/shifterZerus.png',
		'img_discovery': './img/discovery_minion3/shifterZerus.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': {
			'fc': pas_shifterZerus,
			'target': None,
			'buff': None,
			'trigger': 'start_turn',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'soulJunggler': {
		'gold': False,
		'qn': 'Juggler',
		'atk': 3,
		'hp': 3,
		'lvl': 3,
		'archetype': 'neutral',
		'legendary': False,
		'img': './img/minion3/soulJunggler.png',
		'img_discovery': './img/discovery_minion3/soulJunggler.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'theBeast': {
		'gold': False,
		'qn': 'Beast',
		'atk': 9,
		'hp': 7,
		'lvl': 3,
		'archetype': 'beast',
		'legendary': True,
		'img': './img/minion3/theBeast.png',
		'img_discovery': './img/discovery_minion3/theBeast.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'twilightEmissary': {
		'gold': False,
		'qn': 'Twilight',
		'atk': 4,
		'hp': 4,
		'lvl': 3,
		'archetype': 'dragon',
		'legendary': False,
		'img': './img/minion3/twilightEmissary.png',
		'img_discovery': './img/discovery_minion3/twilightEmissary.png',
		'battlecry': {
            'fc': btc_buff_one_minion,
            'target': 'dragon',
            'buff': 2,
        },
		'poisonous': False,
		'taunt': True,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'yoHoOgre': {
		'gold': False,
		'qn': 'Yo-Ho-Ogre',
		'atk': 2,
		'hp': 8,
		'lvl': 3,
		'archetype': 'pirate',
		'legendary': False,
		'img': './img/minion3/yoHoOgre.png',
		'img_discovery': './img/discovery_minion3/yoHoOgre.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': True,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},

    # TIER 2
    'arcaneCannon': {
		'gold': False,
		'qn': 'Cannon',
		'atk': 2,
		'hp': 2,
		'lvl': 2,
		'archetype': 'neutral',
		'legendary': False,
		'img': './img/minion2/arcaneCannon.png',
		'img_discovery': './img/discovery_minion2/arcaneCannon.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'freedealingGambler': {
		'gold': False,
		'qn': 'Gambler',
		'atk': 3,
		'hp': 3,
		'lvl': 2,
		'archetype': 'pirate',
		'legendary': False,
		'img': './img/minion2/freedealingGambler.png',
		'img_discovery': './img/discovery_minion2/freedealingGambler.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': {
			'fc': pas_freedealingGambler,
			'target': None,
			'buff': 3,
			'trigger': 'sold',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'glyphGuardian': {
		'gold': False,
		'qn': 'Guardian',
		'atk': 2,
		'hp': 4,
		'lvl': 2,
		'archetype': 'dragon',
		'legendary': False,
		'img': './img/minion2/glyphGuardian.png',
		'img_discovery': './img/discovery_minion2/glyphGuardian.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'harvestGolem': {
		'gold': False,
		'qn': 'Golem',
		'atk': 2,
		'hp': 3,
		'lvl': 2,
		'archetype': 'meca',
		'legendary': False,
		'img': './img/minion2/harvestGolem.png',
		'img_discovery': './img/discovery_minion2/harvestGolem.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'imprisoner': {
		'gold': False,
		'qn': 'Imprisoner',
		'atk': 3,
		'hp': 3,
		'lvl': 2,
		'archetype': 'demon',
		'legendary': False,
		'img': './img/minion2/imprisoner.png',
		'img_discovery': './img/discovery_minion2/imprisoner.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': True,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'kaboomBot': {
		'gold': False,
		'qn': 'Kaboom',
		'atk': 2,
		'hp': 2,
		'lvl': 2,
		'archetype': 'meca',
		'legendary': False,
		'img': './img/minion2/kaboomBot.png',
		'img_discovery': './img/discovery_minion2/kaboomBot.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'kindlyGrandmother': {
		'gold': False,
		'qn': 'Grandmother',
		'atk': 1,
		'hp': 1,
		'lvl': 2,
		'archetype': 'beast',
		'legendary': False,
		'img': './img/minion2/kindlyGrandmother.png',
		'img_discovery': './img/discovery_minion2/kindlyGrandmother.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'metaltoothLeaper': {
		'gold': False,
		'qn': 'Leaper',
		'atk': 3,
		'hp': 3,
		'lvl': 2,
		'archetype': 'meca',
		'legendary': False,
		'img': './img/minion2/metaltoothLeaper.png',
		'img_discovery': './img/discovery_minion2/metaltoothLeaper.png',
		'battlecry': {
            'fc': btc_buff_atk_all_minion,
            'target': 'meca',
            'buff': 2,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'murlocWarleader': {
		'gold': False,
		'qn': 'Warleader',
		'atk': 3,
		'hp': 3,
		'lvl': 2,
		'archetype': 'murloc',
		'legendary': False,
		'img': './img/minion2/murlocWarleader.png',
		'img_discovery': './img/discovery_minion2/murlocWarleader.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': {
			'fc': pas_murlocWarleader_southseaCaptain_malGanis_siegeBreaker,
			'target': 'murloc',
			'buff': 2,
			'trigger': 'present',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'nathrezimOverseer': {
		'gold': False,
		'qn': 'Overseer',
		'atk': 2,
		'hp': 3,
		'lvl': 2,
		'archetype': 'demon',
		'legendary': False,
		'img': './img/minion2/nathrezimOverseer.png',
		'img_discovery': './img/discovery_minion2/nathrezimOverseer.png',
		'battlecry': {
            'fc': btc_buff_one_minion,
            'target': 'demon',
            'buff': 2,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
    },
    'oldMurkEye': {
		'gold': False,
		'qn': 'Murk-Eye',
		'atk': 2,
		'hp': 4,
		'lvl': 2,
		'archetype': 'murloc',
		'legendary': True,
		'img': './img/minion2/oldMurkEye.png',
		'img_discovery': './img/discovery_minion2/oldMurkEye.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': {
			'fc': pas_oldMurkEye,
			'target': 'murloc',
			'buff': 1,
			'trigger': 'present',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'pogoHopper': {
		'gold': False,
		'qn': 'Pogo',
		'atk': 1,
		'hp': 1,
		'lvl': 2,
		'archetype': 'meca',
		'legendary': False,
		'img': './img/minion2/pogoHopper.png',
		'img_discovery': './img/discovery_minion2/pogoHopper.png',
		'battlecry': {
            'fc': btc_pogoHopper,
            'target': None,
            'buff': 2,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'rabidSaurolisk': {
		'gold': False,
		'qn': 'Saurolisk',
		'atk': 3,
		'hp': 2,
		'lvl': 2,
		'archetype': 'beast',
		'legendary': False,
		'img': './img/minion2/rabidSaurolisk.png',
		'img_discovery': './img/discovery_minion2/rabidSaurolisk.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': {
			'fc': pas_wrathWeaver_saltyLooter_crowdFavorite_rabidSaurolisk,
			'target': 'deathrattle',
			'buff': 1,
			'trigger': 'play',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'ratPack': {
		'gold': False,
		'qn': 'Rat Pack',
		'atk': 2,
		'hp': 2,
		'lvl': 2,
		'archetype': 'beast',
		'legendary': False,
		'img': './img/minion2/ratPack.png',
		'img_discovery': './img/discovery_minion2/ratPack.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'southseaCaptain': {
		'gold': False,
		'qn': 'Captain',
		'atk': 3,
		'hp': 3,
		'lvl': 2,
		'archetype': 'pirate',
		'legendary': False,
		'img': './img/minion2/southseaCaptain.png',
		'img_discovery': './img/discovery_minion2/southseaCaptain.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': {
			'fc': pas_murlocWarleader_southseaCaptain_malGanis_siegeBreaker,
			'target': 'pirate',
			'buff': 1,
			'trigger': 'present',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'spawnOfNzoth': {
		'gold': False,
		'qn': 'Spawn',
		'atk': 2,
		'hp': 2,
		'lvl': 2,
		'archetype': 'neutral',
		'legendary': False,
		'img': './img/minion2/spawnOfNzoth.png',
		'img_discovery': './img/discovery_minion2/spawnOfNzoth.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'stewardOfTime': {
		'gold': False,
		'qn': 'Steward',
		'atk': 3,
		'hp': 4,
		'lvl': 2,
		'archetype': 'dragon',
		'legendary': False,
		'img': './img/minion2/stewardOfTime.png',
		'img_discovery': './img/discovery_minion2/stewardOfTime.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': {
			'fc': pas_stewardOfTime,
			'target': None,
			'buff': 1,
			'trigger': 'sold',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'unstableGhoul': {
		'gold': False,
		'qn': 'Ghoul',
		'atk': 1,
		'hp': 3,
		'lvl': 2,
		'archetype': 'neutral',
		'legendary': False,
		'img': './img/minion2/unstableGhoul.png',
		'img_discovery': './img/discovery_minion2/unstableGhoul.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': True,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'waxriderTogwaggle': {
		'gold': False,
		'qn': 'Towaggle',
		'atk': 1,
		'hp': 2,
		'lvl': 2,
		'archetype': 'neutral',
		'legendary': True,
		'img': './img/minion2/waxriderTogwaggle.png',
		'img_discovery': './img/discovery_minion2/waxriderTogwaggle.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'zoobot': {
		'gold': False,
		'qn': 'Zoobot',
		'atk': 3,
		'hp': 3,
		'lvl': 2,
		'archetype': 'meca',
		'legendary': False,
		'img': './img/minion2/zoobot.png',
		'img_discovery': './img/discovery_minion2/zoobot.png',
		'battlecry': {
            'fc': btc_buff_random_minion,
            'target': ('dragon', 'beast', 'murloc'),
            'buff': 1,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},


	
   # TIER 1
    'alleycat': {
		'gold': False,
		'qn': 'Alleycat',
		'atk': 1,
		'hp': 1,
		'lvl': 1,
		'archetype': 'beast',
		'legendary': False,
		'img': './img/minion1/alleycat.png',
		'img_discovery': './img/discovery_minion1/alleycat.png',
		'battlecry': {
            'fc': btc_token,
            'target': None,
            'buff': None,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'deckSwabbie': {
		'gold': False,
		'qn': 'Swabbie',
		'atk': 2,
		'hp': 2,
		'lvl': 1,
		'archetype': 'pirate',
		'legendary': False,
		'img': './img/minion1/deckSwabbie.png',
		'img_discovery': './img/discovery_minion1/deckSwabbie.png',
		'battlecry': {
            'fc': btc_deckSwabbie,
            'target': None,
            'buff': None,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'dragonspawnLieutenant': {
		'gold': False,
		'qn': 'Lieutenant',
		'atk': 2,
		'hp': 3,
		'lvl': 1,
		'archetype': 'dragon',
		'legendary': False,
		'img': './img/minion1/dragonspawnLieutenant.png',
		'img_discovery': './img/discovery_minion1/dragonspawnLieutenant.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': True,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'fiendishServant': {
		'gold': False,
		'qn': 'Servant',
		'atk': 2,
		'hp': 1,
		'lvl': 1,
		'archetype': 'demon',
		'legendary': False,
		'img': './img/minion1/fiendishServant.png',
		'img_discovery': './img/discovery_minion1/fiendishServant.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'mecharoo': {
		'gold': False,
		'qn': 'Mecharoo',
		'atk': 1,
		'hp': 1,
		'lvl': 1,
		'archetype': 'meca',
		'legendary': False,
		'img': './img/minion1/mecharoo.png',
		'img_discovery': './img/discovery_minion1/mecharoo.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'microMachine': {
		'gold': False,
		'qn': 'Machine',
		'atk': 1,
		'hp': 2,
		'lvl': 1,
		'archetype': 'meca',
		'legendary': False,
		'img': './img/minion1/microMachine.png',
		'img_discovery': './img/discovery_minion1/microMachine.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': {
			'fc': pas_microMachine,
			'target': None,
			'buff': 1,
			'trigger': 'start_turn',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'murlocTidecaller': {
		'gold': False,
		'qn': 'Tidecaller',
		'atk': 1,
		'hp': 2,
		'lvl': 1,
		'archetype': 'murloc',
		'legendary': False,
		'img': './img/minion1/murlocTidecaller.png',
		'img_discovery': './img/discovery_minion1/murlocTidecaller.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': {
			'fc': pas_murlocTidecaller,
			'target': 'murloc',
			'buff': 1,
			'trigger': 'play',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'murlocTidehunter': {
		'gold': False,
		'qn': 'Tidehunter',
		'atk': 2,
		'hp': 1,
		'lvl': 1,
		'archetype': 'murloc',
		'legendary': False,
		'img': './img/minion1/murlocTidehunter.png',
		'img_discovery': './img/discovery_minion1/murlocTidehunter.png',
		'battlecry': {
            'fc': btc_token,
            'target': None,
            'buff': None,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'redWhelp': {
		'gold': False,
		'qn': 'Red Whelp',
		'atk': 1,
		'hp': 2,
		'lvl': 1,
		'archetype': 'dragon',
		'legendary': False,
		'img': './img/minion1/redWhelp.png',
		'img_discovery': './img/discovery_minion1/redWhelp.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'righteousProtector': {
		'gold': False,
		'qn': 'Protector',
		'atk': 1,
		'hp': 1,
		'lvl': 1,
		'archetype': 'neutral',
		'legendary': False,
		'img': './img/minion1/righteousProtector.png',
		'img_discovery': './img/discovery_minion1/righteousProtector.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': True,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': True,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'rockpoolHunter': {
		'gold': False,
		'qn': 'Hunter',
		'atk': 2,
		'hp': 3,
		'lvl': 1,
		'archetype': 'murloc',
		'legendary': False,
		'img': './img/minion1/rockpoolHunter.png',
		'img_discovery': './img/discovery_minion1/rockpoolHunter.png',
		'battlecry': {
            'fc': btc_buff_one_minion,
            'target': 'murloc',
            'buff': 1,
        },
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'scallyWag': {
		'gold': False,
		'qn': 'Scallywag',
		'atk': 2,
		'hp': 1,
		'lvl': 1,
		'archetype': 'pirate',
		'legendary': False,
		'img': './img/minion1/scallyWag.png',
		'img_discovery': './img/discovery_minion1/scallyWag.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'scavengingHyena': {
		'gold': False,
		'qn': 'Hyena',
		'atk': 2,
		'hp': 2,
		'lvl': 1,
		'archetype': 'beast',
		'legendary': False,
		'img': './img/minion1/scavengingHyena.png',
		'img_discovery': './img/discovery_minion1/scavengingHyena.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'selflessHero': {
		'gold': False,
		'qn': 'Selfless',
		'atk': 2,
		'hp': 1,
		'lvl': 1,
		'archetype': 'neutral',
		'legendary': False,
		'img': './img/minion1/selflessHero.png',
		'img_discovery': './img/discovery_minion1/selflessHero.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': False,
		'n_passive': 0,
		'deathrattle': True,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'vulgarHomunculus': {
		'gold': False,
		'qn': 'Homunculus',
		'atk': 2,
		'hp': 4,
		'lvl': 1,
		'archetype': 'demon',
		'legendary': False,
		'img': './img/minion1/vulgarHomunculus.png',
		'img_discovery': './img/discovery_minion1/vulgarHomunculus.png',
		'battlecry': {
            'fc': btc_vulgarHomunculus,
            'target': None,
            'buff': 2,
        },
		'poisonous': False,
		'taunt': True,
		'passive': False,
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
    'wrathWeaver': {
		'gold': False,
		'qn': 'Wrath',
		'atk': 1,
		'hp': 1,
		'lvl': 1,
		'archetype': 'neutral',
		'legendary': False,
		'img': './img/minion1/wrathWeaver.png',
		'img_discovery': './img/discovery_minion1/wrathWeaver.png',
		'battlecry': False,
		'poisonous': False,
		'taunt': False,
		'passive': {
			'fc': pas_wrathWeaver_saltyLooter_crowdFavorite_rabidSaurolisk,
			'target': 'demon',
			'buff': 2,
			'trigger': 'play',
		},
		'n_passive': 0,
		'deathrattle': False,
		'shield': False,
		'reborn': False,
		'magnetic': False,
		'overkill': False,
		'cleave': False,
		'windfury': False,
	},
}

MINION_BY_ARCHETYPE = {
    'dragon': [name for name in MINIONS if MINIONS[name]['archetype'] == 'dragon'],
    'beast': [name for name in MINIONS if MINIONS[name]['archetype'] == 'beast'],
    'murloc': [name for name in MINIONS if MINIONS[name]['archetype'] == 'murloc'],
    'demon': [name for name in MINIONS if MINIONS[name]['archetype'] == 'demon'],
    'pirate': [name for name in MINIONS if MINIONS[name]['archetype'] == 'pirate'],
    'meca': [name for name in MINIONS if MINIONS[name]['archetype'] == 'meca'],
}

MINIONS_BY_TIER = [
    [name for name in MINIONS if MINIONS[name]['lvl'] == 1],
    [name for name in MINIONS if MINIONS[name]['lvl'] == 2],
    [name for name in MINIONS if MINIONS[name]['lvl'] == 3],
    [name for name in MINIONS if MINIONS[name]['lvl'] == 4],
    [name for name in MINIONS if MINIONS[name]['lvl'] == 5],
    [name for name in MINIONS if MINIONS[name]['lvl'] == 6],
]

BUFF_MEGASAUR = {'crackling': 'Shield', 'flaming': '+3attacks', 'spores': 'drt: 2*(1/1)',
    'poison': 'Poisonous', 'massive': 'Taunt', 'volcanic': '+1/+1',
    'lightning': 'Windfury', 'carapace': '+3health'}


    

